build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            - php-scrutinizer-run
            - phpcs-run
            -
                command: './bin/phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
filter:
    excluded_paths:
        - "tests/"

